[build]
  Command = "npm run build"
  Functions = "lambda"
  Publish = "public"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "http://battleexchange.netlify.com/*"
  to = "http://battleexchange.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/battle"
  to = "/battle/sites"
[[redirects]]
  from = "/battle/"
  to = "/battle/sites"