[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "http://battleexchange.netlify.com/*"
  to = "http://battleexchange.com/:splat"
  status = 301
  force = true
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"